# Chapter-5 Collections
This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [131]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating   Activating environment at `D:\julia class\Hands-on-Julia-Programming\Chapter 05\Project.toml`environment at `D:\julia class\Hands-on-Julia-Programming\Chapter 05\Project.toml`



## 5.1 Predefined Data Structures

Julia language has defined a few standard data structures like

- Arrays
- Tuples
- Dicts
- Sets

## 5.2 Tuple

Immutable data type with a number of comma separated values. We have seen tuples as arguments to functions. Here we shall explore the collection like behavior of a tuples.

In [132]:
a = (1, "string", 1.0)


(1, "string", 1.0)

(1, "string", 1.0)

In [133]:
typeof(a)                         # Heterogeneous

Tuple{Int64, String, Float64}

Tuple{Int64, String, Float64}

In [134]:
a[1]                              # Accessed as Index

1

1

In [135]:
a[1] = 6                          # Immutable

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, String, Float64}, ::Int64, ::Int64)

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, String, Float64}, ::Int64, ::Int64)

In [136]:
b, c = a                          # Pattern Matching
(1, "string", 1.0)

(1, "string", 1.0)

(1, "string", 1.0)

In [137]:
b

1

1

In [138]:
c

"string"

"string"

### NTuple

N elements of a specific type in a tuple like collection.

In [139]:
NTuple{3, Int}

Tuple{Int64, Int64, Int64}

Tuple{Int64, Int64, Int64}

In [140]:
a = ntuple(x->4, 10)

(4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

(4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

In [141]:
typeof(a)

NTuple{10, Int64}

NTuple{10, Int64}

In [142]:
a = ntuple(i->i*1.0, 10)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

In [143]:
typeof(a)

NTuple{10, Float64}

NTuple{10, Float64}

### Tuple as a Collection

A `Tuple` has collection like properties like it has length method. Can be iterated over. 

In [144]:
length(a)

10

10

In [145]:
for i=1:length(a)
    println(a[i])
end

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


### Integers as Type Parameters

We saw with `NTuple` an integer `N` being used as a type parameter. We discuss about a Point type which can have N-axes. Then we define Point{2} and Point{3} as special cases for 2 and 3 dimentsions. 

In [146]:
struct Point{N}
    data::NTuple{N, Float32}
    Point(d...)=new{length(d)}(d)
end
const Point2D=Point{2}
const Point3D=Point{3}

function dist(p1::Point2D, p2::Point2D)
    dx, dy = (p1.data[1] - p2.data[1], p1.data[2] - p2.data[2])
    return sqrt(dx*dx+dy*dy)
end
function dist(p1::Point3D, p2::Point3D)
    dx, dy, dz = (p1.data[1] - p2.data[1], 
                  p1.data[2] - p2.data[2], 
                  p1.data[3] - p2.data[3])
    return sqrt(dx*dx+dy*dy+dz*dz)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [147]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

2.828427f0

In [148]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

3.4641016f0

In [149]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [150]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

2.828427f0

In [151]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

3.4641016f0

In [152]:
function dist(p1::Point, p2::Point)
    N = length(p1.data)
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [153]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

2.828427f0

In [154]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))


LoadError: BoundsError: attempt to access Tuple{Float32, Float32} at index [3]

LoadError: BoundsError: attempt to access Tuple{Float32, Float32} at index [3]

In [155]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

function dist(p1::Point{N1}, p2::Point{N2}) where {N1, N2}
    N1 > N2 && return dist(p2, p1)
    tp = Point(p1.data..., ntuple(i->0f0, N2-N1)...)
    return dist(tp, p2)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [156]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))

3.0f0

3.0f0

### Value Parameters

Dispatch based on an integer value. 

In [157]:
struct MyVal{N}
    MyVal(N)=new{N}()
end
f(::MyVal{N}) where N = N
function f(::MyVal{1})
    println("Called from 1")
end

f (generic function with 2 methods)

f (generic function with 2 methods)

In [158]:
f(MyVal(2))

2

2

In [159]:
f(MyVal(1))

Called from 1
Called from 1


#### Singleton

In [160]:
MyVal(1) === MyVal(1)

true

true

In [161]:
MyVal(1) === MyVal(2)

false

false

In [162]:
MyVal(:a)

MyVal{:a}()

MyVal{:a}()

## 5.3 Ranges

Sequence of numbers maintaining a steady pattern. 

### UnitRange
Range of consecutive integers. 

In [163]:
a=1:5
typeof(a)

UnitRange{Int64}

UnitRange{Int64}

In [164]:
for i=a
    println(i)
end

1
2
3
4
5
1
2
3
4
5


### StepRange

Ranges where integers are not consecutive but spaced by a step. 

In [165]:
b=1:2:5
typeof(b)

StepRange{Int64, Int64}

StepRange{Int64, Int64}

In [166]:
for i=b
    println(i)
end

1
3
5
1
3
5


### Decreasing Ranges

Ranges that are decreasing in value with a negative step. 

In [167]:
c=5:-1:1
typeof(c)

StepRange{Int64, Int64}

StepRange{Int64, Int64}

In [168]:
for i=c
    println(i)
end


5
4
3
2
1
5
4
3
2
1


In [169]:
d = 1:2.1:6.0

1.0:2.1:5.2

1.0:2.1:5.2

In [170]:
typeof(d)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

## 5.4 Array
Mutable collection with a well defined memory layout.

In [171]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

3-element Vector{Int64}:
 1
 2
 3

In [172]:
m = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

1×3 Matrix{Int64}:
 1  2  3

In [173]:
m1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [174]:
m2 = [1 2; 3 4; 5 6]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

### Memory Layout and Indexing

In [175]:
m1[1, 2]

2

2

In [176]:
m1[2, 2]

5

5

In [177]:
m2[1, 2]

2

2

In [178]:
m2[2, 2]

4

4

#### Effects of Paging

### Some Useful Functions

#### Constructors

In [179]:
Array{Int}(undef, 1, 2)

1×2 Matrix{Int64}:
 1  1

1×2 Matrix{Int64}:
 1  1

In [180]:
Array{Int}(undef, 2)

2-element Vector{Int64}:
 0
 0

2-element Vector{Int64}:
 0
 0

In [181]:
Array{Int, 2}(undef, (2, 3))

2×3 Matrix{Int64}:
 1805112688  283167280  1806766608
 1800763936  310804512   310772016

2×3 Matrix{Int64}:
 1805112688  283167280  1806766608
 1800763936  310804512   310772016

In [182]:
Array{Float32}(undef, (2, 3))

2×3 Matrix{Float32}:
 5.01262f-28  5.01263f-28  5.01265f-28
 0.0          0.0          0.0

2×3 Matrix{Float32}:
 5.01262f-28  5.01263f-28  5.01265f-28
 0.0          0.0          0.0

In [183]:
struct A
    i::Int
    f::Float64
end
a = A(1, 1); isbits(a)

true

true

In [184]:
aarr = Array{A}(undef, (2, 2))

2×2 Matrix{A}:
 A(140722297006081, 4.94e-322)  A(20, 1.5e-323)
 A(1000, 1.235e-321)            A(32, 2.0e-323)

2×2 Matrix{A}:
 A(140722297006081, 4.94e-322)  A(20, 1.5e-323)
 A(1000, 1.235e-321)            A(32, 2.0e-323)

In [185]:
struct T
    a::A
    b
end
b = T(A(1, 1), 1); isbits(b)

false

false

In [186]:
barr = Array{T}(undef, (2, 2))

2×2 Matrix{T}:
 #undef  #undef
 #undef  #undef

2×2 Matrix{T}:
 #undef  #undef
 #undef  #undef

In [187]:
barr[1,1] = barr[2,1] = barr[1,2] = barr[2,2] = b

T(A(1, 1.0), 1)

T(A(1, 1.0), 1)

In [188]:
barr

2×2 Matrix{T}:
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)

2×2 Matrix{T}:
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)

In [189]:
Vector{Int}(undef, 3)

3-element Vector{Int64}:
 0
 0
 0

3-element Vector{Int64}:
 0
 0
 0

In [190]:
Matrix{Int}(undef, 3, 3)

3×3 Matrix{Int64}:
 1803453136  1800745040  257819712
  257819440   257819536  282810480
 1800745040  1802370096  282810800

3×3 Matrix{Int64}:
 1803453136  1800745040  257819712
  257819440   257819536  282810480
 1800745040  1802370096  282810800

#### zeros and ones

In [191]:
zeros(Float32, (2, 3))

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [192]:
ones(Float32, (2, 3))

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [193]:
ones(UInt8, (2, 3))

2×3 Matrix{UInt8}:
 0x01  0x01  0x01
 0x01  0x01  0x01

2×3 Matrix{UInt8}:
 0x01  0x01  0x01
 0x01  0x01  0x01

#### trues and falses

Return `BitArray`, which are optimal `Array{Bool}` like types but take 1/8-th of the space. 

In [194]:
zb = zeros(Bool, (8, 8))

8×8 Matrix{Bool}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

8×8 Matrix{Bool}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [195]:
sizeof(zb)

64

64

In [196]:
z = falses(8, 8)

8×8 BitMatrix:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

8×8 BitMatrix:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [197]:
sizeof(z)

8

8

#### fill and similar

In [198]:
a = fill(5.0, (2, 2))

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [199]:
a = fill(5, (2, 2))

2×2 Matrix{Int64}:
 5  5
 5  5

2×2 Matrix{Int64}:
 5  5
 5  5

In [200]:
b = similar(a, Int)

2×2 Matrix{Int64}:
  277106448  277106464
 1800745040          2

2×2 Matrix{Int64}:
  277106448  277106464
 1800745040          2

#### collect

Enumerates over a collection and return an array with all elements populated. 

In [201]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

3-element Vector{Int64}:
 1
 2
 3

In [202]:
collect(Float64, 1:2:3)

2-element Vector{Float64}:
 1.0
 3.0

2-element Vector{Float64}:
 1.0
 3.0

#### reshape

Reshape an array to various sizes while keeping the row major ordering intact.

In [203]:
a = collect(1:16)

16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

In [204]:
b = reshape(a, (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [205]:
c = reshape(b, (2, 8))

2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

In [206]:
d = reshape(c, (8, 2))

8×2 Matrix{Int64}:
 1   9
 2  10
 3  11
 4  12
 5  13
 6  14
 7  15
 8  16

8×2 Matrix{Int64}:
 1   9
 2  10
 3  11
 4  12
 5  13
 6  14
 7  15
 8  16

#### hcat, vcat and hvcat

Concatenation of arrays vertically, horizontally or both when the dimensions are aligned properly. 

In [207]:
vcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

6×2 Matrix{Int64}:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

6×2 Matrix{Int64}:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [208]:
hcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

2×6 Matrix{Int64}:
 1  2  5  6   9  10
 3  4  7  8  11  12

2×6 Matrix{Int64}:
 1  2  5  6   9  10
 3  4  7  8  11  12

In [209]:
hvcat((2, 2, 2), [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

6×2 Matrix{Int64}:
  1   3
  2   4
  5   7
  6   8
  9  11
 10  12

6×2 Matrix{Int64}:
  1   3
  2   4
  5   7
  6   8
  9  11
 10  12

In [210]:
hvcat(6, [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

## 5.5 Associative Collection

A collection where a key and value are kept associated. The keys are used for accessing the elements of the collection. 

### Dict

A hash based dictionary.

In [211]:
d = Dict("a"=>1, "c"=>2, "b"=>3)

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 1

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 1

In [212]:
d["b"]

3

3

In [213]:
d["a"] = 5

5

5

In [214]:
println(d)

Dict("c" => 2, "b" => 3, "a" => 5)
Dict("c" => 2, "b" => 3, "a" => 5)


In [215]:
d = Dict("a"=>1, "c"=>2, "b"=>3, "a"=>4)

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 4

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 4

#### get Methods

In [216]:
get(d, "a", 3)

4

4

In [217]:
get(d, "e", 0)

0

0

In [218]:
getindex(d, "e")

LoadError: KeyError: key "e" not found

LoadError: KeyError: key "e" not found

In [219]:
d["e"]

LoadError: KeyError: key "e" not found

LoadError: KeyError: key "e" not found

In [220]:
get!(d, "a", 0)

4

4

In [221]:
get!(d, "e", 0)

0

0

In [222]:
d

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 0
  "b" => 3
  "a" => 4

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 0
  "b" => 3
  "a" => 4

#### setindex! Method

In [223]:
d["e"] = 10

10

10

In [224]:
setindex!(d, 11, "e")

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 11
  "b" => 3
  "a" => 4

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 11
  "b" => 3
  "a" => 4

### Set

Collection of belonging. Unique elements only. 

In [225]:
s = Set([2 3 4 5 1 2 3])

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [226]:
6 in s

false

false

In [227]:
5 in s

true

true

In [228]:
t = Set([4 5 7 8 9])

Set{Int64} with 5 elements:
  5
  4
  7
  9
  8

Set{Int64} with 5 elements:
  5
  4
  7
  9
  8

#### Union and Intersection

In [229]:
union(s, t)

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

In [230]:
intersect(s, t)

Set{Int64} with 2 elements:
  5
  4

Set{Int64} with 2 elements:
  5
  4

In [231]:
union!(s, t)

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

In [232]:
s

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

## 5.6 Iteration 

All collections are enabled for iteration. This requires the collections to implement certain interfaces / functions. 

### for loop

In [233]:
for i=5:-2:1
    println(i)
end

5
3
1
5
3
1


In [234]:
b = [1.0 2 3; 4 5 6; 7 8 9]
for i=b
    println(i)
end

1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0
1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0


In [235]:
for p in d
    println(p)
end

"c" => 2
"e" => 11
"b" => 3
"a" => 4
"c" => 2
"e" => 11
"b" => 3
"a" => 4


In [236]:
for (k, v) in d
    println("Key:", k," Value:", v)
end

Key:c Value:2
Key:e Value:11
Key:b Value:3
Key:a Value:4
Key:c Value:2
Key:e Value:11
Key:b Value:3
Key:a Value:4


### function...do

A very neat way to code for function that applies to every element of the collection. `map` is a useful method that is in-built to address such needs. 

In [237]:
function collect_square(v)
    a = similar(v)
    for i=1:length(v)
        a[i] = v[i]*v[i]
    end
    return a
end
collect_square(1:4)

4-element Vector{Int64}:
  1
  4
  9
 16

4-element Vector{Int64}:
  1
  4
  9
 16

In [238]:
function collect_function(f::Function, v)
    a = similar(v)
    for i=1:length(v)
        a[i] = f(v[i])
    end
    return a
end
collect_function(x->x^3, 1:4)

4-element Vector{Int64}:
  1
  8
 27
 64

4-element Vector{Int64}:
  1
  8
 27
 64

In [239]:
collect_function(1:4) do x
    return x^3
end

4-element Vector{Int64}:
  1
  8
 27
 64

4-element Vector{Int64}:
  1
  8
 27
 64

In [240]:
map(1:4) do x
    return x^3
end

4-element Vector{Int64}:
  1
  8
 27
 64

4-element Vector{Int64}:
  1
  8
 27
 64

## 5.7 Iteration Framework

Custom collection authors must implement the iteration framework. 

In [241]:
v = collect(3:2:10)

4-element Vector{Int64}:
 3
 5
 7
 9

4-element Vector{Int64}:
 3
 5
 7
 9

In [242]:
for i=v
    println(i)
end

3
5
7
9
3
5
7
9


In [243]:
next = iterate(v)

(3, 2)

(3, 2)

In [244]:
while next !== nothing
    value, state = next
    println(value)
    next = iterate(v, state)
end


3
5
7
9
3
5
7
9


### iterate Methods

### Optional Methods

In [245]:
Base.IteratorSize(Vector{Int})

Base.HasShape{1}()

Base.HasShape{1}()

In [246]:
Base.IteratorEltype(Vector{Int})

Base.HasEltype()

Base.HasEltype()

In [247]:
eltype(Vector{Int})

Int64

Int64

### Example

In [248]:
struct Squares
    value::Int
end
Base.iterate(s::Squares) = s.value <= 0 ? nothing : (1, 2)

Base.iterate(s::Squares, state) = s.value < state ? nothing :      
    (state*state, state+1)

In [249]:
for i=Squares(3)
    println(i)
end

1
4
9
1
4
9


In [250]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

In [251]:
Base.length(s::Squares)=s.value

In [252]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

In [253]:
Base.eltype(::Type{Squares})=Int

In [254]:
eltype(Squares)

Int64

Int64

In [255]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

## 5.8 Generators and Comprehensions

Comprehensions are a simple notation to create arrays. Generators provide the iterator interface and elements get computed only when iterated upon. 

In [256]:
[i*i for i=1:3]

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

In [257]:
[i*j for i=1:3, j=1:3]

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [258]:
[i*j for i=1:3 for j=i:3]

6-element Vector{Int64}:
 1
 2
 3
 4
 6
 9

6-element Vector{Int64}:
 1
 2
 3
 4
 6
 9

In [259]:
gen=(i*j for i=1:3 for j=i:3)

Base.Iterators.Flatten{Base.Generator{UnitRange{Int64}, var"#46#47"}}(Base.Generator{UnitRange{Int64}, var"#46#47"}(var"#46#47"(), 1:3))

Base.Iterators.Flatten{Base.Generator{UnitRange{Int64}, var"#46#47"}}(Base.Generator{UnitRange{Int64}, var"#46#47"}(var"#46#47"(), 1:3))

In [260]:
for v=gen
    println(v)
end

1
2
3
4
6
9
1
2
3
4
6
9
